version: '3.8'

services:
  nextjs:
    container_name: tokomatra_nextjs
    restart: always
    image: ghcr.io/bagasstr/toko-matrakosala:0.2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tokomatra
      - DATABASE_URL=${DATABASE_URL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL=${EMAIL}
      - NEXT_PUBLIC_MERCHANT_ID=${NEXT_PUBLIC_MERCHANT_ID}
      - MIDTRANS_CLIENT_KEY=${MIDTRANS_CLIENT_KEY}
      - MIDTRANS_SERVER_KEY=${MIDTRANS_SERVER_KEY}
      - NEXT_PUBLIC_LOGO_BASE64=${NEXT_PUBLIC_LOGO_BASE64}
    depends_on:
      - postgres
    volumes:
      - /mnt/nas/docker-data/toko_matra/toko_matra_app:/app
      - /app/node_modules
      - /app/.next
      - /mnt/nas/docker-data/toko_matra:/app/public
    networks:
      - ix-cloudflared_default
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run seed &&
        node server.js
      "

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db_tokomatra
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tokomatra
    ports:
      - '4321:5432'
    volumes:
      - /mnt/nas/docker-data/postgres_tokomatra:/var/lib/postgresql/data
    networks:
      - ix-cloudflared_default

volumes:
  postgres-data:
    driver: local
networks:
  ix-cloudflared_default:
    external: true
    name: ix-cloudflared_default
